Odin-SMR/odin-api

.gitmodules, Jenkinsfile
This should build on Molflow's Jenkins, updated submodule to load data from Odin-SMR
=> removing phabricator build feedback

src/odinapi/templates/level2.html, src/systemtest/test_browser.py
Resolves: https://github.com/molflow/odin/issues/1
=> Added the list and a test for its existance

scripts/docker-compose.deploy.yml, src/MANIFEST.in
Odin-api needs access the credentials to the cdsapi. Removed an outdated file from when we used setup.py to install the system.
=> deployment

package-lock.json, package.json
Updated major versions of some karma plugins - that resolved many of the issues but not all. There is still one dependency pulling in a "faulty" version of minimist.
=> Resolved some issues with ncu and check-outdated

package-lock.json, package.json, src/odinapi/utils/encrypt_util.py
following
https://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-aes
Resolves #7 together with PR 8 in qqjobs repo
=> Encrypt data with AES

src/examples/get_l2_data.py, src/odinapi/templates/dataaccess.html
=> document how to use paging of endpoints

src/odinapi/templates/index.html
After discussing with @donal-mur I have removed the caution news item. Also fixed a typo. This resolves part of #57.
=> Removed caution news item and fixed typo

src/examples/vds_example.py, src/odinapi/templates/dataaccess.html
Add information on the VDS API and a downloadable example to the data access page.
Resolves #74
=> VDS example

src/odinapi/templates/layout.html
This is part of #76 , just adding a link under the **Data browser** menu.
We've also been asked to add a news item, but haven't received the copy yet.
=> link to mesospheo

package-lock.json, package.json
Bara att mergea för den som godkänner (givet att alla tester fått ✅ )
=> Upgrade chromedriver

requirements.in, requirements.txt, src/scripts/getsolar.sh, src/scripts/processsolar.py
We run getsolar.sh script in a crontab, within the odin-api container, on malachite.
The scripts directory is mounted in /app/scripts in the odin-api container,
The processsolar script was not running as this script was not found.
Resolves #104
=> fixing broken updating of solardb

src/odinapi/templates/index.html
Adding acknowledgement to SNIC.
This is how it looks:
=> adding acknowledgement

package-lock.json, package.json
bump karma in order to resolve https://github.com/Odin-SMR/odin-api/security/dependabot/package-lock.json/xmlhttprequest-ssl/open
=> bump karma

.github/workflows/ci.yml, .npmrc, Dockerfile, docker-compose.systemtest.yml, package-lock.json, package.json, src/odinapi/templates/index.html, tox.ini
Adding DOIs to Odin products. Below is a screenshot showing how this will appear on the main view:
Resolves #116
=> adding dois

.github/workflows/ci.yml, Dockerfile, package-lock.json, src/odinapi/static/js/level1statistics.js
The problem was with how the imports were done. See https://github.com/Odin-SMR/odin-api/commit/d66f708c2c8dba561d81b7f19f36629fdafdb3dd for the actual operational change.
In following commits, I have looked at linting and bringing the code quality up to speed (fixing everything to be up to eslint standard is unreasonable, I think, but now it is at least readable in VSC).
Resolves #118
=> fix imports

package-lock.json, requirements.in, requirements.txt, src/odinapi/templates/index.html
This adds a warning to users in the the SANOMA banner and in addition fixes a few dependency issues we've accrued.
=> Add warning to SANOMA section

.github/workflows/cd.yaml
build and push image to ECR
update service to run new image
=> Continuous deployment to ECS

.gitignore, Dockerfile, compose.yaml, entrypoint.sh, gunicorn.conf.py, logconf.yaml, requirements-dev.txt, requirements.in, requirements.txt, services/proxy/odin.conf, src/odinapi/api.py, src/odinapi/database/mongo.py, src/odinapi/templates/dataaccess.html, src/odinapi/views/database.py
add gunicorn configfile
logging controlable via dictconfig
remove auth on mongo (not accessable outside VPC)
more logging on mongo
link l2 nc-files on bucket
add postgres certificate
=> Run smoothly on ECS

src/odinapi/views/views.py
This add some logging around the lock for the raw endpoints.
=> Add logging around lock

.gitignore, gunicorn.conf.py, logconf.yaml, requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt, src/conftest.py, src/odinapi/api.py, src/odinapi/database/mongo.py, src/odinapi/odin_config.py, src/odinapi/run.py, src/odinapi/views/level2.py, src/systemtest/api/test_project_annotations.py, src/systemtest/level2_test_data.py, src/systemtest/test_browser.py, src/systemtest/test_examples.py, src/systemtest/test_level1.py, src/systemtest/test_level1_cached.py, src/systemtest/test_level2.py, src/systemtest/test_swagger.py, src/test/database/test_level2db.py, src/test/database/test_projectsdb.py, src/test/test_smrl2filewriter.py, src/test/views/test_views.py, start
add start script to run app locally
move all flask-config options to app.config object run tests on local flask app
keep docker compose testing for swagger,apriori and vds
=> Test as local as possible

.github/workflows/cd.yaml, .github/workflows/ci.yml, package-lock.json, src/odinapi/views/read_ptz.py
The API can't find ZPT, even though they exist. This causes QSMR to run with out "Pressure", "Temperature" and "Altitude" fields.
=> Empty S3 cache
